[package]
name = "kean"
version = "0.1.0"
edition = "2024"

[dependencies]
# Add dependencies here as needed, for example:
# serde = { version = "1.0", features = ["derive"] } # For serialization if you plan to create a REST API
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
